In [6]:
import pandas as pd

In [7]:
path = 'https://raw.githubusercontent.com/subashgandyer/datasets/main/loan_train.csv'

In [9]:
# Now reading the data
df = pd.read_csv(path)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
Loan_ID              614 non-null object
Gender               601 non-null object
Married              611 non-null object
Dependents           599 non-null object
Education            614 non-null object
Self_Employed        582 non-null object
ApplicantIncome      614 non-null int64
CoapplicantIncome    614 non-null float64
LoanAmount           592 non-null float64
Loan_Amount_Term     600 non-null float64
Credit_History       564 non-null float64
Property_Area        614 non-null object
Loan_Status          614 non-null object
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB


In [11]:
df.isna().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [12]:
df['Gender'].mode()
df['Gender'].fillna('male',inplace=True)

df['Married'].mode()
df['Married'].fillna('Yes',inplace=True)

df['Self_Employed'].mode()
df['Self_Employed'].fillna('Yes',inplace=True)

df['Dependents'] = data['Dependents'].replace(['3+'],3)
df['Dependents'].fillna(0,inplace=True)
df['Dependents'].fillna(0,inplace=True)

df.fillna(data.mean(),inplace=True)

In [13]:
df.isna().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

# CATEGORICAL DATA TO NUMERICAL DATA

In [14]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
le = LabelEncoder()

In [15]:
df.Gender = le.fit_transform(df.Gender)

df.Married = le.fit_transform(df.Married)

df.Self_Employed = le.fit_transform(df.Self_Employed)

df.Education = le.fit_transform(df.Education)
                                  
df.Loan_Status = le.fit_transform(df.Loan_Status)

In [16]:
ohe = OneHotEncoder()
area = ohe.fit_transform(data[['Property_Area']]).toarray()
a_frame = pd.DataFrame(area)

data_new = pd.concat([data,a_frame],axis=1)

In [17]:
data_new

Loan_ID  Gender  Married Dependents  Education  Self_Employed  \
0    LP001002       1        0          0          0              0   
1    LP001003       1        1          1          0              0   
2    LP001005       1        1          0          0              1   
3    LP001006       1        1          0          1              0   
4    LP001008       1        0          0          0              0   
..        ...     ...      ...        ...        ...            ...   
609  LP002978       0        0          0          0              0   
610  LP002979       1        1          3          0              0   
611  LP002983       1        1          1          0              0   
612  LP002984       1        1          2          0              0   
613  LP002990       0        0          0          0              1   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5849                0.0  146.412162             360.0   
1               4583             1508.0  128.000000             360.0   
2               3000                0.0   66.000000             360.0   
3               2583             2358.0  120.000000             360.0   
4               6000                0.0  141.000000             360.0   
..               ...                ...         ...               ...   
609             2900                0.0   71.000000             360.0   
610             4106                0.0   40.000000             180.0   
611             8072              240.0  253.000000             360.0   
612             7583                0.0  187.000000             360.0   
613             4583                0.0  133.000000             360.0   

     Credit_History Property_Area  Loan_Status    0    1    2  
0               1.0         Urban            1  0.0  0.0  1.0  
1               1.0         Rural            0  1.0  0.0  0.0  
2               1.0         Urban            1  0.0  0.0  1.0  
3               1.0         Urban            1  0.0  0.0  1.0  
4               1.0         Urban            1  0.0  0.0  1.0  
..              ...           ...          ...  ...  ...  ...  
609             1.0         Rural            1  1.0  0.0  0.0  
610             1.0         Rural            1  1.0  0.0  0.0  
611             1.0         Urban            1  0.0  0.0  1.0  
612             1.0         Urban            1  0.0  0.0  1.0  
613             0.0     Semiurban            0  0.0  1.0  0.0  

[614 rows x 16 columns]

# DATA SPLITTING, DEPENDENT AND INDEPENDENT VARIABLES

In [14]:
X = df_new.loc[:,['Gender','Married','Dependents','Education','Self_Employed','ApplicantIncome','CoapplicantIncome','LoanAmount','Loan_Amount_Term','Credit_History',0,1,2]]
y = df['Loan_Status']

In [15]:
X

Gender  Married Dependents  Education  Self_Employed  ApplicantIncome  \
0         1        0          0          0              0             5849   
1         1        1          1          0              0             4583   
2         1        1          0          0              1             3000   
3         1        1          0          1              0             2583   
4         1        0          0          0              0             6000   
..      ...      ...        ...        ...            ...              ...   
609       0        0          0          0              0             2900   
610       1        1          3          0              0             4106   
611       1        1          1          0              0             8072   
612       1        1          2          0              0             7583   
613       0        0          0          0              1             4583   

     CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History    0  \
0                  0.0  146.412162             360.0             1.0  0.0   
1               1508.0  128.000000             360.0             1.0  1.0   
2                  0.0   66.000000             360.0             1.0  0.0   
3               2358.0  120.000000             360.0             1.0  0.0   
4                  0.0  141.000000             360.0             1.0  0.0   
..                 ...         ...               ...             ...  ...   
609                0.0   71.000000             360.0             1.0  1.0   
610                0.0   40.000000             180.0             1.0  1.0   
611              240.0  253.000000             360.0             1.0  0.0   
612                0.0  187.000000             360.0             1.0  0.0   
613                0.0  133.000000             360.0             0.0  0.0   

       1    2  
0    0.0  1.0  
1    0.0  0.0  
2    0.0  1.0  
3    0.0  1.0  
4    0.0  1.0  
..   ...  ...  
609  0.0  0.0  
610  0.0  0.0  
611  0.0  1.0  
612  0.0  1.0  
613  1.0  0.0  

[614 rows x 13 columns]

In [16]:
y

0      1
1      0
2      1
3      1
4      1
      ..
609    1
610    1
611    1
612    1
613    0
Name: Loan_Status, Length: 614, dtype: int32

# DATA SPLITTING, TRAIN AND TEST

In [17]:
from sklearn.model_selection import train_test_split
train_X,test_X,train_y,test_y = train_test_split(X, y,train_size=0.5,test_size=0.5,random_state=123) 

# DATA PREPROCESSING

In [18]:
from sklearn.preprocessing import scale,MinMaxScaler
min_max = MinMaxScaler()

In [19]:
x_train_minMax = min_max.fit_transform(train_X)
x_test_minMax = min_max.fit_transform(test_X)

# DECISION TREE ALGORITHM 

In [20]:
from sklearn.tree import DecisionTreeClassifier
tree = DecisionTreeClassifier(criterion='gini',max_depth=None)

In [21]:
tree.fit(x_train_minMax,train_y)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [22]:
prediction = tree.predict(x_test_minMax)

In [23]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(test_y,prediction))

[[ 47  56]
 [ 51 153]]


In [24]:
param_dist = {'criterion': ['gini','entropy'], 'max_depth': [1,2,3,4,5,6,7,None]} 

In [25]:
from sklearn.model_selection import GridSearchCV 

In [26]:
grid = GridSearchCV(tree, param_grid=param_dist, cv=10, n_jobs=-1) 

In [27]:
grid.fit(x_train_minMax,train_y)

C:\Users\MATTHEW\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


GridSearchCV(cv=10, error_score='raise-deprecating',
             estimator=DecisionTreeClassifier(class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features=None,
                                              max_leaf_nodes=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              presort=False, random_state=None,
                                              splitter='best'),
             iid='warn', n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [1, 2, 3, 4, 5, 6, 7, None]},
          

In [28]:
grid.best_params_

{'criterion': 'gini', 'max_depth': 1}

In [29]:
grid.best_estimator_

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=1,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [30]:
grid_predictions = grid.predict(x_test_minMax)

In [31]:
print(confusion_matrix(test_y,grid_predictions),'\n with accuracy ',grid.best_score_)

[[ 43  60]
 [  4 200]] 
 with accuracy  0.8273615635179153


# KNN ALGORITHM 

In [32]:
from sklearn.neighbors import KNeighborsClassifier

Knn = KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [33]:
Knn.fit(train_X,train_y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [34]:
K_prediction = Knn.predict(test_X)

In [35]:
print(confusion_matrix(test_y,K_prediction))

[[ 12  91]
 [ 29 175]]


In [36]:
param_distK = {'n_neighbors' : [5,7,9,11,13,15],
               'weights' : ['uniform','distance'],
               'metric' : ['minkowski','euclidean','manhattan']} 

In [37]:
K_grid = GridSearchCV(KNeighborsClassifier(), param_distK, verbose = 1, cv=3, n_jobs = -1)

In [38]:
K_grid.fit(train_X,train_y)

Fitting 3 folds for each of 36 candidates, totalling 108 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done 108 out of 108 | elapsed:    0.3s finished
C:\Users\MATTHEW\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


GridSearchCV(cv=3, error_score='raise-deprecating',
             estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30,
                                            metric='minkowski',
                                            metric_params=None, n_jobs=None,
                                            n_neighbors=5, p=2,
                                            weights='uniform'),
             iid='warn', n_jobs=-1,
             param_grid={'metric': ['minkowski', 'euclidean', 'manhattan'],
                         'n_neighbors': [5, 7, 9, 11, 13, 15],
                         'weights': ['uniform', 'distance']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=1)

In [39]:
K_grid.best_params_

{'metric': 'minkowski', 'n_neighbors': 11, 'weights': 'uniform'}

In [40]:
K_grid.best_estimator_

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=11, p=2,
                     weights='uniform')

In [41]:
grid_predictionsK = K_grid.predict(test_X)

In [42]:
print(confusion_matrix(test_y,grid_predictionsK),'\n with accuracy ',K_grid.best_score_)

[[ 10  93]
 [ 18 186]] 
 with accuracy  0.742671009771987


# REGRESSION ALGORITHM 

In [43]:
import numpy as np
from sklearn.linear_model import LogisticRegression

logReg = LogisticRegression()

In [44]:
logReg.fit(train_X,train_y)

C:\Users\MATTHEW\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [45]:
Reg_prediction = logReg.predict(test_X)

In [46]:
print(confusion_matrix(test_y,Reg_prediction))

[[ 44  59]
 [  4 200]]


In [47]:
param_dist_reg = {'penalty' : ['l1', 'l2', 'elasticnet', 'none'],
    'C' : np.logspace(-4, 4, 20),
    'solver' : ['lbfgs','newton-cg','liblinear','sag','saga'],
    'max_iter' : [100, 1000,2500, 5000]
    }

In [48]:
reg_grid = GridSearchCV(logReg, param_grid = param_dist_reg, verbose = 1, cv=3, n_jobs = -1)

In [49]:
reg_grid.fit(train_X,train_y)

Fitting 3 folds for each of 1600 candidates, totalling 4800 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.


ValueError: Solver lbfgs supports only 'l2' or 'none' penalties, got l1 penalty.

In [ ]:
reg_grid.best_params_

In [ ]:
reg_grid.best_estimator_

In [50]:
grid_predictionsReg = reg_grid.predict(test_X)

NotFittedError: This GridSearchCV instance is not fitted yet. Call 'fit' with appropriate arguments before using this method.

In [51]:
print(confusion_matrix(test_y,grid_predictionsReg),'\n with accuracy ',reg_grid.best_score_)

NameError: name 'grid_predictionsReg' is not defined

# SVM ALGORITHM 

In [18]:
from sklearn.svm import SVC
svm_model = SVC(C= 1, gamma= 0.01, kernel= 'rbf', random_state=50)

In [19]:
svm_model.fit(train_X,train_y)

NameError: name 'train_X' is not defined

In [20]:
print(confusion_matrix(test_y,prediction_svm))

NameError: name 'confusion_matrix' is not defined

In [56]:
param_grid_svm = {'C': [0.1,1, 10, 100, 1000], 'gamma': [1,0.1,0.01,0.001,0.0001], 'kernel': ['rbf']} 

In [57]:
grid_svm = GridSearchCV(SVC(),param_grid_svm,refit=True,verbose=3)

In [58]:
grid_svm.fit(train_X,train_y)

C:\Users\MATTHEW\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.0s remaining:    0.0s


Fitting 3 folds for each of 25 candidates, totalling 75 fits
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.709, total=   0.0s
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.709, total=   0.0s
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.713, total=   0.0s
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................
[CV] ........ C=0.1, gamma=0.1, kernel=rbf, score=0.709, total=   0.0s
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................
[CV] ........ C=0.1, gamma=0.1, kernel=rbf, score=0.709, total=   0.0s
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................
[CV] ........ C=0.1, gamma=0.1, kernel=rbf, score=0.713, total=   0.0s
[CV] C=0.1, gamma=0.01, kernel=rbf ...................................
[CV] ....... C=0

[Parallel(n_jobs=1)]: Done  75 out of  75 | elapsed:    0.7s finished


GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='auto_deprecated', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='warn', n_jobs=None,
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
                         'kernel': ['rbf']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=3)

In [59]:
grid_svm.best_params_

{'C': 1, 'gamma': 0.001, 'kernel': 'rbf'}

In [60]:
grid_svm.best_estimator_

SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [61]:
grid_prediction_svm = grid.predict(test_X)

In [62]:
print(confusion_matrix(test_y,grid_prediction_svm),'\n with accuracy ',grid_svm.best_score_)

[[ 43  60]
 [  4 200]] 
 with accuracy  0.7166123778501629


# RANDOM FOREST ALGORITHM 

In [63]:
from sklearn.ensemble import RandomForestClassifier
rf_model = RandomForestClassifier(random_state =0, n_estimators=100)

In [64]:
rf_model.fit(train_X,train_y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [65]:
prediction_rf = rf_model.predict(test_X)

In [66]:
print(confusion_matrix(test_y,prediction_rf))

[[ 43  60]
 [ 11 193]]


In [67]:
param_grid_rf = {'bootstrap': [True, False],
 'max_depth': [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, None],

 'n_estimators': [200, 400, 600]}

In [68]:
grid_rf = GridSearchCV(estimator = rf_model, param_grid = param_grid_rf,  cv = 3, verbose=2)

In [69]:
grid_rf.fit(train_X,train_y)

Fitting 3 folds for each of 66 candidates, totalling 198 fits
[CV] bootstrap=True, max_depth=10, n_estimators=200 ..................
[CV] ... bootstrap=True, max_depth=10, n_estimators=200, total=   0.2s
[CV] bootstrap=True, max_depth=10, n_estimators=200 ..................


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.1s remaining:    0.0s


[CV] ... bootstrap=True, max_depth=10, n_estimators=200, total=   0.2s
[CV] bootstrap=True, max_depth=10, n_estimators=200 ..................
[CV] ... bootstrap=True, max_depth=10, n_estimators=200, total=   0.2s
[CV] bootstrap=True, max_depth=10, n_estimators=400 ..................
[CV] ... bootstrap=True, max_depth=10, n_estimators=400, total=   0.4s
[CV] bootstrap=True, max_depth=10, n_estimators=400 ..................
[CV] ... bootstrap=True, max_depth=10, n_estimators=400, total=   0.3s
[CV] bootstrap=True, max_depth=10, n_estimators=400 ..................
[CV] ... bootstrap=True, max_depth=10, n_estimators=400, total=   0.4s
[CV] bootstrap=True, max_depth=10, n_estimators=600 ..................
[CV] ... bootstrap=True, max_depth=10, n_estimators=600, total=   0.5s
[CV] bootstrap=True, max_depth=10, n_estimators=600 ..................
[CV] ... bootstrap=True, max_depth=10, n_estimators=600, total=   0.5s
[CV] bootstrap=True, max_depth=10, n_estimators=600 ..................
[CV] .

[Parallel(n_jobs=1)]: Done 198 out of 198 | elapsed:  1.4min finished
C:\Users\MATTHEW\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


GridSearchCV(cv=3, error_score='raise-deprecating',
             estimator=RandomForestClassifier(bootstrap=True, class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features='auto',
                                              max_leaf_nodes=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              n_estimators=100, n_jobs=None,
                                              oob_score=False, random_state=0,
                                              verbose=0, warm_start=False),
             iid='warn', n_jobs=None,
             param_grid={'boot

In [70]:
grid_rf.best_params_

{'bootstrap': True, 'max_depth': 10, 'n_estimators': 600}

In [71]:
grid_rf.best_estimator_

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=10, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=600,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [72]:
grid_prediction_rf = grid_rf.predict(test_X)

In [73]:
print(confusion_matrix(test_y,grid_prediction_rf),'\n with accuracy ',grid_rf.best_score_)

[[ 43  60]
 [  6 198]] 
 with accuracy  0.8208469055374593
